#!/usr/bin/env bash
#
# Cross-compile the chaaga-cli CLI and publish the binaries as a GitHub release.
#
# Usage:
#   ./publish.sh <version> [flags]
#
#   version        REQUIRED. e.g. 1.4.0 or v1.4.0 — no default, so a bare
#                  `./publish.sh` never publishes anything. The release is
#                  tagged "v<version>" (matching install.sh, which resolves
#                  the latest release from GitHub). For a throwaway build with
#                  no release, use `go build` directly (see README).
#
#   --skip-tests   don't run `go vet` / `go test ./...` before building
#   --draft        create the release as a draft
#   --prerelease   mark the release as a prerelease (implied for -rc/-alpha/-beta)
#   --notes TEXT   release notes body (default: autogenerated from git log)
#
# Requires: go, gh (authenticated — run `gh auth login`).

set -euo pipefail

cd "$(dirname "$0")"

REPO=chaaga-world/chaaga-cli
BIN=chaaga-cli
DIST=dist
PLATFORMS=(
  "darwin/arm64"
  "darwin/amd64"
  "linux/amd64"
  "linux/arm64"
  "windows/amd64"
)

version=""
skip_tests=0
draft=0
prerelease=0
notes=""

while [ $# -gt 0 ]; do
  case "$1" in
    --skip-tests) skip_tests=1 ;;
    --draft) draft=1 ;;
    --prerelease) prerelease=1 ;;
    --notes) notes="${2:-}"; shift ;;
    -h|--help) sed -n '2,19p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    -*) echo "unknown flag: $1" >&2; exit 2 ;;
    *)
      if [ -z "$version" ]; then version="$1"; else
        echo "unexpected argument: $1" >&2; exit 2
      fi
      ;;
  esac
  shift
done

if [ -z "$version" ]; then
  echo "publish.sh: a version is required, e.g. ./publish.sh 1.4.0" >&2
  echo "            (for a local build with no release, just run: go build -o chaaga-cli .)" >&2
  echo >&2
  if command -v gh >/dev/null && gh auth status >/dev/null 2>&1; then
    echo "Published releases on $REPO:" >&2
    rels="$(gh release list --repo "$REPO" --limit 15 2>/dev/null || true)"
    if [ -n "$rels" ]; then
      printf '%s\n' "$rels" | sed 's/^/  /' >&2
    else
      echo "  (none yet)" >&2
    fi
  fi
  exit 2
fi
version="${version#v}"
tag="v${version}"
case "$version" in
  *-rc*|*-alpha*|*-beta*) prerelease=1 ;;
esac

command -v go >/dev/null || { echo "go not found on PATH" >&2; exit 1; }
command -v gh >/dev/null || { echo "gh not found on PATH — https://cli.github.com" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "gh is not authenticated — run: gh auth login" >&2; exit 1; }

if [ "$skip_tests" -eq 0 ]; then
  echo ">> go vet ./..."
  go vet ./...
  echo ">> go test ./..."
  go test ./...
fi

commit="$(git rev-parse --short HEAD)"
full_commit="$(git rev-parse HEAD)"
branch="$(git rev-parse --abbrev-ref HEAD)"
date="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# The release tag points at target_commitish, which GitHub only accepts if it
# resolves on the remote — an unpushed local commit fails with HTTP 422. Prefer
# the exact commit when it's already on origin, otherwise fall back to the
# branch name (its remote tip) and say so.
if git branch -r --contains HEAD 2>/dev/null | grep -q .; then
  target="$full_commit"
else
  target="$branch"
  echo ">> warning: HEAD ($commit) isn't pushed to origin — the release will" >&2
  echo "   point at origin/$branch's tip, not your local commit." >&2
fi
ldflags="-s -w -X main.version=${version} -X main.commit=${commit} -X main.buildDate=${date}"

rm -rf "$DIST"
mkdir -p "$DIST"

echo ">> building ${BIN} ${version} (${commit})"
for platform in "${PLATFORMS[@]}"; do
  os="${platform%/*}"
  arch="${platform#*/}"
  out="${DIST}/${BIN}-${os}-${arch}"
  [ "$os" = "windows" ] && out="${out}.exe"
  echo "   ${os}/${arch} -> ${out}"
  CGO_ENABLED=0 GOOS="$os" GOARCH="$arch" \
    go build -trimpath -ldflags "$ldflags" -o "$out" .
done

echo ">> checksums"
( cd "$DIST" && shasum -a 256 * > SHA256SUMS && cat SHA256SUMS )

if [ -z "$notes" ]; then
  notes="Automated \`chaaga-cli\` build at commit ${commit}."
fi

gh_args=( "$tag" "$DIST"/* --repo "$REPO" --title "chaaga-cli ${version}" --notes "$notes" --target "$target" )
[ "$draft" -eq 1 ] && gh_args+=( --draft )
[ "$prerelease" -eq 1 ] && gh_args+=( --prerelease )

if gh release view "$tag" --repo "$REPO" >/dev/null 2>&1; then
  echo ">> release ${tag} exists — uploading assets with --clobber"
  gh release upload "$tag" "$DIST"/* --repo "$REPO" --clobber
else
  echo ">> creating release ${tag}"
  gh release create "${gh_args[@]}"
fi

echo ">> done: $(gh release view "$tag" --repo "$REPO" --json url --jq .url)"
